# Generated by Django 4.2.2 on 2023-06-25 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_alter_customer_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetails',
            name='book',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='books.book'),
        ),
    ]
