# Generated by Django 4.2.2 on 2023-06-26 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_alter_book_is_favorite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booksfavorites',
            name='book',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='books.book'),
        ),
    ]
