# Generated by Django 4.2.2 on 2023-06-26 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_alter_booksfavorites_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booksfavorites',
            name='customer',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='books.customer'),
        ),
    ]
