# Generated by Django 4.2.2 on 2023-06-26 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_alter_booksfavorites_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booksfavorites',
            name='book',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='books.book'),
        ),
        migrations.AlterField(
            model_name='booksfavorites',
            name='customer',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='books.customer'),
        ),
    ]
