# Generated by Django 4.2.2 on 2023-07-14 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_alter_booksfavorites_book_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='is_favorite',
            new_name='is_series',
        ),
        migrations.AddField(
            model_name='book',
            name='image',
            field=models.CharField(default='static/default-image.png', max_length=300),
        ),
    ]
