# Generated by Django 4.2.2 on 2023-07-14 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0010_rename_is_favorite_book_is_series_book_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publisher',
            old_name='Name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='auther',
            name='user',
        ),
        migrations.AddField(
            model_name='auther',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
