# Generated by Django 4.2.2 on 2023-07-14 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0011_rename_name_publisher_name_remove_auther_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(default='static/default-image.png', upload_to='book_images'),
        ),
    ]
